### PR TITLE
Add feature A

### PR DESCRIPTION
**Pull request by jay-brdy**
Completed feature A by adding a inspirational quote.

### CODE REVIEW

**Comment by nesibenur** [comment]
lgtm!

**Comment by jay-brdy** [comment]
`Confirm that **feature-A** has been merged into main by navigating back to the repo's main page. The README should now have the **line that Student A added**.`

Uhmm... so the main is showing the line that Student B added. I believe you were supposed to Merge Pull Request for Feature A! 

That is fine though, we can work through it. Just keep in mind that in the other steps where it says `confirm that feature-B has been merged into main` that we will be looking for feature-A instead. 

**The end goal is to have BOTH lines we created added to README.md so I think we should be okay!**

**Comment by nesibenur** [comment]
I am so sorry I didnt realized it

**Comment by jay-brdy** [comment]
It's ok! We will adjust for it :-)

**Pull request merged**
